### ISSUE TITLE
2019计划

### ISSUE THREAD

**Issue by zibuyu1995** [zibuyu1995/Blog#26]
之前一直打算写一下2019年的计划，由于重构项目一直没时间去考虑，更多可能是因为个人私事耽搁了，转眼就毕业1年半了，个人技术成长减缓了很多，来自家里以及生活中的压力越来越大，2019年希望能获得更纯粹一点吧

2019年计划
* 用C++ 考过CCF认证(350+)
* 雅思能达到6以上
* 熟练使用C++
* 学会用golang写一些小工具
* 写一个开源分布式队列(python)
* 去做一件自己一直要去做的事，不管成功还是失败

**Comment by ttop5** [comment]
最后一件事是表白么？ 233

**Comment by zibuyu1995** [comment]
我靠，你居然可以看到

**Comment by ttop5** [comment]
😶
